### ISSUE TITLE
De-couple Wireguard requirement

### ISSUE THREAD

**Issue by chiefy** [Billos/Broadcastarr#2]
Any reason you are hard-coding Wireguard in the compose orchestration? I get why you _might_ want to use a VPN to grab certain data/scrapes, but IMO it should be up to the operator to take care of this and they might already have something they're using (think Gluetun, or VPN via egress routes).

**Comment by Billos** [comment]
I basically just kept the compose I've been using for dev, I'll simplify it to offer an out of the box docker without VPN

**Comment by Billos** [comment]
Done
