### ISSUE TITLE
Bootstrap fails with build 1.1.0

### ISSUE THREAD

**Issue by aurvandel** [Billos/Broadcastarr#4]
I pulled release 1.1.0 and am no longer able to bootstrap with the new changes. I get the following error.

`(node:40) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
bootstrap-1  | (Use `node --trace-warnings ...` to show where the warning was created)
bootstrap-1  | /app/build/bootstrap.js:2
bootstrap-1  | import { bootstrappers } from "./bootstrappers";
bootstrap-1  | ^^^^^^
bootstrap-1  |
bootstrap-1  | SyntaxError: Cannot use import statement outside a module
bootstrap-1  |     at wrapSafe (node:internal/modules/cjs/loader:1469:18)
bootstrap-1  |     at Module._compile (node:internal/modules/cjs/loader:1491:20)
bootstrap-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
bootstrap-1  |     at Module.load (node:internal/modules/cjs/loader:1317:32)
bootstrap-1  |     at Module._load (node:internal/modules/cjs/loader:1127:12)
bootstrap-1  |     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
bootstrap-1  |     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
bootstrap-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:166:5)
bootstrap-1  |     at node:internal/main/run_main_module:30:49
bootstrap-1  |
bootstrap-1  | Node.js v22.6.0
bootstrap-1  | error Command failed with exit code 1.
bootstrap-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
bootstrap-1  | error Command failed with exit code 1.`

I tried the easy answers from google by adding "type": "module" to package.config but that doesn't work. I can get farther in the bootstrap process by changing the imports to requires but that would require a lot of changes. I'm not familiar enough with JS and the changes you've made to know if that is the best option but I'm assuming it's not.

**Comment by Billos** [comment]
Ok, that's what I've been working on the whole afternoon >_<
I'm just gonna run everything with tsx and check this later
