### ISSUE TITLE
Questions to add to documentation

### ISSUE THREAD

**Issue by aurvandel** [Billos/Broadcastarr#6]
I have a few questions regarding the environment variables that I think would be good to add to the documentation as well. Specifically, what do I put for the following variables?
DESTINATION=
BROADCASTARR_REMOTE_URL=

Also, what would I put in GROUPS and CATEGORIES_EMOJIS for American Football? I tried using American Football in both but the space in between broke things.

Thanks.

**Comment by Billos** [comment]
Hi, yes there's a lack of information concerning the M3U8 destination folder, I'll do this.

I'm not sure the categories can contain a space, I'll check this out too

**Comment by aurvandel** [comment]
Replying to my own questions. I assumed that remote url was whatever I assigned to my reverse proxy but I couldn't get it to work. I think it's because I have my services distributed so I had to open up the server port by adding it to the docker compose file for the server and then resetting the ports to an empty list for the worker.

**Comment by aurvandel** [comment]
> Hi, yes there's a lack of information concerning the M3U8 destination folder, I'll do this.
> 
> I'm not sure the categories can contain a space, I'll check this out too

For my purposes it's fine if I can't put American Football in. I only watch a half a dozen games a year but others may feel different.

**Comment by giannihill** [comment]
> Replying to my own questions. I assumed that remote url was whatever I assigned to my reverse proxy but I couldn't get it to work. I think it's because I have my services distributed so I had to open up the server port by adding it to the docker compose file for the server and then resetting the ports to an empty list for the worker.

I also did this and did an override stack because it was throwing a worker error bc of the extends.

**Comment by Billos** [comment]
Oh right I didn't think about it that way as I'm almost never exposing the port.
The extends was interesting to avoid having a big compose file, but I might give up on this, it's not the first time it is causing problems

**Comment by aurvandel** [comment]
Here's all I added
`server:
    image: docker.io/billos/broadcastarr:1.2.0
    command: "server"
    volumes:
      - ${M3U8_FOLDER}:${M3U8_FOLDER}:rw
    env_file:
      - .env
    ports:
      - 8989:8989
    environment:
      NODE_ENV: development
      LOG_LEVEL: 3
      MONGO_URL: mongodb://mongo:27017
      MONGO_AGENDA_DB: agenda
      MONGO_DB: broadcastarr
    deploy:
      resources:
        limits:
          memory: 4g
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy

  worker:
    extends:
      service: server
    container_name: worker
    ports: !reset []
    command: "worker"`

**Comment by giannihill** [comment]
for some reason !reset [] wasn't working for me, which is why I went with the override stack.

also confused about the DESTINATION variable fwiw

**Comment by Billos** [comment]
Destination is replaced by M3U8_FOLDER, it's clearer

**Comment by Billos** [comment]
Concerning the space in categories, the only issue I had was the creation of Matrix channels, which is fixed, make sure that you wrap the value with quotes in the env files @aurvandel

**Comment by Billos** [comment]
> env_file:

Do you know if I can reset the field networks of a container, and set a new list of networks ?

**Comment by Billos** [comment]
> Here's all I added
> 
> ```
> server:
>     image: docker.io/billos/broadcastarr:1.2.0
>     command: "server"
>     volumes:
>       - ${M3U8_FOLDER}:${M3U8_FOLDER}:rw
>     env_file:
>       - .env
>     ports:
>       - 8989:8989
>     environment:
>       NODE_ENV: development
>       LOG_LEVEL: 3
>       MONGO_URL: mongodb://mongo:27017
>       MONGO_AGENDA_DB: agenda
>       MONGO_DB: broadcastarr
>     deploy:
>       resources:
>         limits:
>           memory: 4g
>     restart: unless-stopped
>     depends_on:
>       mongo:
>         condition: service_healthy
> 
>   worker:
>     extends:
>       service: server
>     container_name: worker
>     ports: !reset []
>     command: "worker"
> ```

@aurvandel Do you know if I can reset the field networks of a container, and set a new list of networks ?
