### ISSUE TITLE
Sample indexer json

### ISSUE THREAD

**Issue by giannihill** [Billos/Broadcastarr#7]
Can you provide a sample working indexer json? And/or help troubleshoot what's happening here... Tested the two in there and getting following log issues

worker  | 2024-12-02 18:54:07.046 DEBUG         log:BroadcastsIndexer       getCategoryLink         Indexer              Streamed                       category             Basketball                     url https://streamed.su/ Found 56 links
worker  | 2024-12-02 18:54:07.047 DEBUG         log:BroadcastsIndexer       getCategoryLink         Indexer              Streamed                       category             Basketball                     url https://streamed.su/ Looking for Basketball
worker  | 2024-12-02 18:54:07.047 INFO  log:BroadcastsIndexer       getCategoryLink         Indexer              Streamed                       category             Basketball                     url https://streamed.su/ Found category link https://streamed.su/category/basketball
worker  | 2024-12-02 18:54:07.058 DEBUG         log:BroadcastsIndexer       getCategoryLink         Indexer              Sport365                       category             Football                       url https://live.sport365.stream/ Found 27 links
worker  | 2024-12-02 18:54:07.059 DEBUG         log:BroadcastsIndexer       getCategoryLink         Indexer              Sport365                       category             Football                       url https://live.sport365.stream/ Looking for Soccer
worker  | 2024-12-02 18:54:07.060 INFO  log:BroadcastsIndexer       getCategoryLink         Indexer              Sport365                       category             Football                       url https://live.sport365.stream/ Found category link https://sport365.stream/soccer
worker  | 2024-12-02 18:54:07.649 DEBUG         log:GenericBroadcastsInd... getBroadcastsData       category             Football                       url                  https://sport365.stream/soccer Parsing page  1
worker  | 2024-12-02 18:54:07.738 INFO  log:GenericBroadcastsInd... parseCurrentPage        category             Football                                                                            Found 1 broadcast sets
worker  | 2024-12-02 18:54:07.738 DEBUG         log:GenericBroadcastsInd... parseBroadcastSet       category             Football                                                                            Parsing broadcast set
worker  | 2024-12-02 18:54:07.947 INFO  log:GenericBroadcastsInd... parseBroadcastSet       category             Football                                                                            Found 20 broadcast blocks
worker  | 2024-12-02 18:54:07.948 DEBUG         log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Parsing 20 blocks
worker  | 2024-12-02 18:54:08.004 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:08.056 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:08.199 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:08.383 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:08.475 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:08.663 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:08.800 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:08.937 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:09.011 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:09.169 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:09.355 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:09.448 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:09.554 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:09.747 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:09.923 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:10.021 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:10.116 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:10.257 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:10.439 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:10.579 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLocaleLowerCase')
worker  | 2024-12-02 18:54:10.626 ERROR         log:BroadcastsIndexer       generate                Indexer              Sport365                       category             Football                        Error: Invalid number value
worker  |     at Object.getNumberConfig (/app/build/modules/config/controller.js:12:15)
worker  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
worker  |     at async DynamicBroadcastsIndexer.shouldStopParsing (/app/build/modules/indexers/genericBroadcastsIndexer.js:177:29)
worker  |     at async DynamicBroadcastsIndexer.getBroadcastsData (/app/build/modules/indexers/genericBroadcastsIndexer.js:34:32)
worker  |     at async DynamicBroadcastsIndexer.generate (/app/build/modules/indexers/broadcastsIndexer.js:63:36)
worker  |     at async Object.handler (/app/build/modules/agenda/handlers/indexCategory.js:21:27)
worker  |     at async Job.runJob (/app/node_modules/@hokify/agenda/src/Job.ts:494:4)
worker  |     at async Job.run (/app/node_modules/@hokify/agenda/src/Job.ts:426:5)
worker  |     at async JobProcessor.runOrRetry (/app/node_modules/@hokify/agenda/src/JobProcessor.ts:563:5)
worker  | 2024-12-02 18:54:10.627 WARN  log:BroadcastsIndexer       generate                Indexer              Sport365                       category             Football                        No data found
worker  | 2024-12-02 18:54:10.683 INFO  log:Scrapper                getBrowser                                                                                                                       Browser disconnected
worker  | 2024-12-02 18:54:11.419 INFO  log:IndexCategoryHandler    handler                 category             Football                       indexer              Sport365                        0 broadcasts found
worker  | 2024-12-02 18:54:11.420 ERROR         log:AgendaDefiner           onFail                                                                                                                           Job "IndexCategory" failed with error: Invalid number value - data: {"category":"Football","indexerName":"Sport365"}
worker  | 2024-12-02 18:54:11.422 INFO  log:AgendaDefiner           onFail                                                                                                                           Rescheduling IndexCategory in 60 seconds - Mon Dec 02 2024 18:55:11 GMT-0500 (Eastern Standard Time)
worker  | 2024-12-02 18:54:16.845 DEBUG         log:BroadcastsIndexer       getCategoryLink         Indexer              Streamed                       category             Football                       url https://streamed.su/ Getting page https://streamed.su/ with element { path: 'div.w-full div.flex a' }
worker  | 2024-12-02 18:54:17.202 ERROR         log:BroadcastsIndexer       generate                Indexer              Streamed                       category             Basketball                      TimeoutError: Waiting for selector `div.flex-row` failed: Waiting failed: 10000ms exceeded
worker  |     at new WaitTask (/app/node_modules/puppeteer-core/src/common/WaitTask.ts:76:28)
worker  |     at BidiFrameRealm.waitForFunction (/app/node_modules/puppeteer-core/src/api/Realm.ts:74:22)
worker  |     at Function.waitFor (/app/node_modules/puppeteer-core/src/common/QueryHandler.ts:170:50)
worker  |     at async BidiFrame.waitForSelector (/app/node_modules/puppeteer-core/src/api/Frame.ts:731:13)
worker  |     at async BidiPage.waitForSelector (/app/node_modules/puppeteer-core/src/api/Page.ts:2948:12)
worker  |     at async DynamicBroadcastsIndexer.getPage (/app/build/modules/indexers/scrapper.js:115:9)
worker  |     at async DynamicBroadcastsIndexer.getBroadcastsData (/app/build/modules/indexers/genericBroadcastsIndexer.js:19:22)
worker  |     at async DynamicBroadcastsIndexer.generate (/app/build/modules/indexers/broadcastsIndexer.js:63:36)
worker  |     at async Object.handler (/app/build/modules/agenda/handlers/indexCategory.js:21:27)
worker  |     at async Job.runJob (/app/node_modules/@hokify/agenda/src/Job.ts:494:4)
worker  | 2024-12-02 18:54:17.202 WARN  log:BroadcastsIndexer       generate                Indexer              Streamed                       category             Basketball                      No data found
worker  | 2024-12-02 18:54:17.214 INFO  log:Scrapper                getBrowser                                                                                                                       Browser disconnected

**Comment by Billos** [comment]
I think I found most of the issue, in the data.broadcast.group[0] can you replace group into name in the regex and the default values ?

**Comment by giannihill** [comment]
> I think I found most of the issue, in the data.broadcast.group[0] can you replace group into name in the regex and the default values ?

I don't think I understand what you mean... just delete group node from broadcast (data.broadcast.group) since name node already exists? Here's the section 

```java
"broadcast": {
      "selector": [ { "path": "div.pb-1" } ],
      "startTime": [
        { "path": "span.left-2", "format": "h:mm a", "attribute": null },
        { "path": "div.py-4 p span:nth-child(2)", "format": "| h:mm a", "attribute": null }
      ],
      "link": [
        { "path": "a", "attribute": "href" }
      ],
      "name": [
        { 
          "path": "h1",
          "replacement": {
            "regex": " (vs|v) ",
            "replace": " 🆚 "
          }
        }
      ],
      "group": []
    }
```

**Comment by Billos** [comment]
> > I think I found most of the issue, in the data.broadcast.group[0] can you replace group into name in the regex and the default values ?
> 
> I don't think I understand what you mean... just delete group node from broadcast (data.broadcast.group) since name node already exists? Here's the section
> 
> ```java
> "broadcast": {
>       "selector": [ { "path": "div.pb-1" } ],
>       "startTime": [
>         { "path": "span.left-2", "format": "h:mm a", "attribute": null },
>         { "path": "div.py-4 p span:nth-child(2)", "format": "| h:mm a", "attribute": null }
>       ],
>       "link": [
>         { "path": "a", "attribute": "href" }
>       ],
>       "name": [
>         { 
>           "path": "h1",
>           "replacement": {
>             "regex": " (vs|v) ",
>             "replace": " 🆚 "
>           }
>         }
>       ],
>       "group": []
>     }
> ```
Try this for group
      "group": [
        {
          "path": "div.schedule__match span.competition-text",
          "regex": "((?<country>.+)\\. )?(?<name>.+)",
          "default": { "country": "World", "name": "Ungrouped" }
        }
      ]

**Comment by giannihill** [comment]
For the Sport365 default, that is throwing the below warning...I don't think I can tell from the log which variable(s) (group, group.name, group.country, name, country) might be the issue?
```shell
worker  | 2024-12-03 17:08:40.020 DEBUG         log:GenericBroadcastsInd... getGroup                name                 Sport365                                                                            Checking if group is active
worker  | 2024-12-03 17:08:40.020 DEBUG         log:GenericBroadcastsInd... getGroup                name                 Sport365                                                                            Group is not inactive
worker  | 2024-12-03 17:08:40.020 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLowerCase')
worker  | 2024-12-03 17:08:40.068 DEBUG         log:GenericBroadcastsInd... getGroup                name                 Sport365                                                                            Checking if group is active
worker  | 2024-12-03 17:08:40.068 DEBUG         log:GenericBroadcastsInd... getGroup                name                 Sport365                                                                            Group is not inactive
worker  | 2024-12-03 17:08:40.069 WARN  log:GenericBroadcastsInd... parseBroadcasts         category             Football                                                                            Cannot read properties of undefined (reading 'toLowerCase')
``` 
Would it make sense to update something [here](https://github.com/Billos/Broadcastarr/blob/c453e8a4b9b8e0bad7b5b6d942442bc0951f104a/src/modules/indexers/genericBroadcastsIndexer.ts#L215C89-L215C90) to check for undefined and pass a dummy value before it applies the toLowerCase standardiation?

**Comment by Billos** [comment]
If you updated the indexer, it shouldn't be undefined.

But yes I should think of something safer here

**Comment by giannihill** [comment]
Yeah I spun it up in a fresh container and I'm still getting that error...going to try and troubleshoot later tonight and see if I can find some clues as to whether it's a different setting that has me messed up.

**Comment by giannihill** [comment]
this is the .json file i'm using

https://pastebin.com/2NK8i8Sm

**Comment by Billos** [comment]
Can you try this ? 
https://pastebin.com/G3ETZmKx

**Comment by giannihill** [comment]
it seems to be still throwing that error (worker log attached)...I'm going to try build and run from a different host tomorrow

[_worker_logs.txt](https://github.com/user-attachments/files/18046276/_worker_logs.txt)

**Comment by Billos** [comment]
Did you run the bootstrap to update the value in the db ?

**Comment by giannihill** [comment]
Finally had some free time to rebuild it, seems to be working now! Games are getting pushed to Discord channels. Thank you for your help @Billos

**Comment by Billos** [comment]
Great !
