### ISSUE TITLE
Questions on Setup

### ISSUE THREAD

**Issue by ronnoceel** [Billos/Broadcastarr#8]
Hello,

Thank you for sharing this project. I am interested but I am still unsure about how to best integrate it into my stack. I have a few questions that I hope you can help me with.

1. Are the discord/matrix bots necessary for this to function? I don't use either of these often. I can't tell from the readme if these are simply a convenient interface for commands or if they are actually necessary to run. For instance, if I don't mind changing the config by hand when I want to add/change a category, can I only use the config and never run either of these bots?
2. I use [gluetun](https://github.com/qdm12/gluetun) to connect with my VPN, as to many who run similar stacks. Is there a way to use it instead or do I need to use wireguard? Can I forgo the vpn entirely while I am testing? If so, how?
3. This might be a more general question but:I am running this on a single host with very few users. Do I need to use workers? Can I just have it running in a single instance? 
4. I would like to eventually integrate this into my current stack instead of running it separately. Do you plan on having a fully built image that I can just add to my master docker compose file?

Again, thank you for your work on this. I have been thinking about something like this for a while and it's cool that you've actually implemented it.

**Comment by Billos** [comment]
Hello !

1. You have options in the bootstrap env variables, that will define if you want to use the Discord / Matrix / Gotify publishers, the Discord Bot is also optional in the server env var. You can activate or deactivate stuff straight from the mongodb, but it won't trigger all the Agenda tasks, it might work for some basic changes, but I can't guarantee that everything will work
2. My wireguard connection is pretty much a working draft, I haven't been using gluetun, so I don't know if my configuration would work with it, however you can try naming it "wireguard" and check the default route too see if the containers are using it. But if it doesn't work the default route should remain unchanged, it shouldn't break anything.
3. The server does not run the tasks, it's more comfortable during dev to avoid massive restarts but I could add an option. This being said, I think the server consumption is negligible, I don't think there is so much interest in sparing 1 container
4. The docker-compose.yml file should be an "out of the box" solution for this, but let me know if you have more technical questions about it

Thanks ! Don't hesitate to contribute if you want to help improve it :)

**Comment by ronnoceel** [comment]
You say in the documentation "accessible by the Jellyfin container too at the same path". Can I instead recommend this be a docker volume? My Jellyfin instance is running in docker and I can't really see a path to having Jellyfin and broadcastarr access the same file using the same path.
